# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5be2e3ebd1655dd9f69182b811cdc7852a5b15870b70cf316832207d3f7619030a3d9bba77c213864152c41fba2fdc5b089bde3e9d6af8741e6ea554e009f426

test:
  secret_key_base: 8ceba3cff7374f856d70f0e3b59b0fcefd7de128a9d55bc40b7e9821d55336db71d3b5125235f7e9d6e3ab74ac3c99cc14770771f6ad6cccc59724f9f6c9775a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
